// <auto-generated />
using AppStatistics.Core.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AppStatistics.Core.Migrations
{
    [DbContext(typeof(ReportingContext))]
    partial class ReportingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("AppStatistics.Core.Data.Sqlite.SqlApplication", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("active");

                    b.Property<string>("analyticsEndpoint");

                    b.Property<string>("applicationName");

                    b.Property<DateTime>("creationDate");

                    b.Property<string>("description");

                    b.HasKey("id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("AppStatistics.Core.Data.Sqlite.SqlEvent", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("active");

                    b.Property<string>("applicationID");

                    b.Property<string>("category");

                    b.Property<string>("message");

                    b.Property<string>("metadata");

                    b.Property<DateTime>("timestamp");

                    b.HasKey("id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("AppStatistics.Core.Data.Sqlite.SqlException", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SqlExceptionid");

                    b.Property<bool>("active");

                    b.Property<string>("applicationID");

                    b.Property<int>("hresult");

                    b.Property<string>("message");

                    b.Property<string>("metadata");

                    b.Property<int>("severity");

                    b.Property<string>("stackTrace");

                    b.Property<DateTime>("timeStamp");

                    b.HasKey("id");

                    b.HasIndex("SqlExceptionid");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("AppStatistics.Core.Data.Sqlite.SqlException", b =>
                {
                    b.HasOne("AppStatistics.Core.Data.Sqlite.SqlException")
                        .WithMany("innerExceptions")
                        .HasForeignKey("SqlExceptionid");
                });
#pragma warning restore 612, 618
        }
    }
}
